
package com.web.service.phone;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PhoneService", targetNamespace = "http://phone.service.web.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PhoneService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.web.service.phone.Phone
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPhoneInfo", targetNamespace = "http://phone.service.web.com/", className = "com.web.service.phone.GetPhoneInfo")
    @ResponseWrapper(localName = "getPhoneInfoResponse", targetNamespace = "http://phone.service.web.com/", className = "com.web.service.phone.GetPhoneInfoResponse")
    @Action(input = "http://phone.service.web.com/PhoneService/getPhoneInfoRequest", output = "http://phone.service.web.com/PhoneService/getPhoneInfoResponse")
    public Phone getPhoneInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
